### ISSUE TITLE
CreateFromFormat factory & timezone

### ISSUE THREAD

**Issue by widoz** [Rarst/wpdatetime#5]
I see that the method [WpDateTimeTrait::createFromPost](https://github.com/Rarst/wpdatetime/blob/master/src/WpDateTimeTrait.php#L26) doesn't get passed the time zone that instead is constructed within it

```
$wp_timezone = WpDateTimeZone::getWpTimezone();
$create_timezone = new \DateTimeZone( 'UTC' );
```

More over the timezone finally set for the newly `$wp_time` will be always `$wp_timezone` this because of the following code

```
$wp_time = new static( $post_date, $create_timezone );
return $wp_time->setTimezone( $wp_timezone );
```

Shouldn't be just `$wp_timezone` ?
Also, why not just allow the client decide which timezone set for the DateTime instance?

Ps. Just curious, why if the gmt isn't set you switch to use wp_timezone?

**Comment by Rarst** [comment]
> Shouldn't be just $wp_timezone ?

I don't follow the question. Shouldn't what?

> Also, why not just allow the client decide which timezone set for the DateTime instance?

Because WP time zone is sensible default in WP environment and specifying time zone isn't _necessary_ for the operation (unlike `createFromFormat()`). It's trivial to set object to a desired timezone after and not worth making API more complex.

> Ps. Just curious, why if the gmt isn't set you switch to use wp_timezone?

Because local times in database are presumed to be in WP timezone and need to be parsed as such.

Does this answer your questions? :)

**Comment by widoz** [comment]
> Shouldn't be just $wp_timezone ?
>> I don't follow the question. Shouldn't what?

Why not just do `$wp_time = new static( $post_date, $wp_timezone );` ?

> Ps. Just curious, why if the gmt isn't set you switch to use wp_timezone?
>> Because local times in database are presumed to be in WP timezone and need to be parsed as such.

I don't get it, what's difference with the `DateTimeZone('UTC')` and `WpDateTimeZone::getWpTimezone()`?

I see it's only because of the internal value, but at the end if you'll set the value of `WpDateTimeZone::getWpTimezone()` means there's no differences.

**Comment by Rarst** [comment]
> Why not just do $wp_time = new static( $post_date, $wp_timezone ); ?

Because if `$post_date` is sourced from `gmt` field then parsing it with non-UTC timezone will lead to invalid result.

> I see it's only because of the internal value, but at the end if you'll set the value of WpDateTimeZone::getWpTimezone() means there's no differences.

There are two different timezone operations in there:

1. Parsing post data. This will use UTC **or** WP timezone, depending if we parse `gmt` **or** local time respectively.
2. Returning object. This will _always_ use WP timezone as sensible default for the context.

**Comment by widoz** [comment]
Ah I see, thank you.
